---
- name: 'Ensure packages'
  ansible.builtin.package:
    name:
      - 'dhcp-server'
      - 'tftp-server'
      - 'syslinux'
    state: 'present'

- name: 'Ensure configuration files'
  ansible.builtin.template:
    src: "{{ config['src'] }}"
    dest: "{{ config['dest'] }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: "{{ config['notify'] }}"
  loop:
    - src: 'dhcpd.conf.j2'
      dest: '/etc/dhcp/dhcpd.conf'
      notify: 'Restart dhcpd'
  loop_control:
    loop_var: 'config'

- name: 'Ensure bootloader files'
  ansible.builtin.copy:
    src: "/usr/share/syslinux/{{ bootloader }}"
    dest: "/var/lib/tftpboot/{{ bootloader }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
    remote_src: true
  loop:
    - 'ldlinux.c32'
    - 'libutil.c32'
    - 'menu.c32'
    - 'pxelinux.0'
  loop_control:
    loop_var: 'bootloader'

- name: 'Download Boot ISO'
  ansible.builtin.get_url:
    url: "{{ edge_image_builder_bootiso_download }}"
    dest: '/var/cache/osbuild-composer/boot.iso'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Extract boot images from ISO'
  community.general.iso_extract:
    image: '/var/cache/osbuild-composer/boot.iso'
    dest: '/var/www/html'
    files:
      - 'images/install.img'
      - 'images/pxeboot/initrd.img'
      - 'images/pxeboot/vmlinuz'

- name: 'Ensure services'
  ansible.builtin.service:
    name: "{{ service }}"
    state: 'started'
    enabled: true
  loop:
    - 'dhcpd'
    - 'tftp'
  loop_control:
    loop_var: 'service'
