---
- name: 'Assert supported system'
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == 'RedHat'

- name: 'Ensure dependencies'
  ansible.builtin.package:
    name:
      - 'osbuild-composer'
      - 'composer-cli'
      - 'httpd'
    state: 'present'
  notify: 'Reboot system'

- name: 'Ensure services'
  ansible.builtin.service:
    name: "{{ service }}"
    state: 'started'
    enabled: true
  loop:
    - 'osbuild-composer.socket'
    - 'httpd.service'
  loop_control:
    loop_var: 'service'

- name: 'Get distro ID'
  ansible.builtin.shell: |
    set -o pipefail
    . /etc/os-release
    echo $ID
  register: 'edge_image_builder_distro_id_raw'
  changed_when: false

- name: 'Set fact for distro ID'
  ansible.builtin.set_fact:
    edge_image_builder_distro_id: "{{ edge_image_builder_distro_id_raw['stdout'] }}-{{ ansible_facts['distribution_major_version'] }}"

- name: 'Ensure directories'
  ansible.builtin.file:
    path: "{{ directory }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  loop:
    - '/etc/osbuild-composer/repositories'
    - '/etc/osbuild-composer/blueprints'

- name: 'Ensure default repository overrides'
  ansible.builtin.template:
    src: "{{ edge_image_builder_distro_id }}.json.j2"
    dest: "/etc/osbuild-composer/repositories/{{ edge_image_builder_distro_id }}.json"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart osbuild-composer'

- name: 'Ensure extra repo definitions'
  ansible.builtin.template:
    src: 'osbuild-composer-repo.toml.j2'
    dest: "/etc/osbuild-composer/repositories/{{ repo['id'] }}.toml"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ edge_image_builder_repos }}"
  loop_control:
    loop_var: 'repo'

- name: 'Import extra repo definitions'
  ansible.builtin.command: /usr/bin/composer-cli sources add /etc/osbuild-composer/repositories/{{ repo['id'] }}.toml
  changed_when: true  # The command does not tell you if anything has changed
  loop: "{{ edge_image_builder_repos }}"
  loop_control:
    loop_var: 'repo'

- name: 'Configure deployment server'
  ansible.builtin.include_tasks: 'tasks/deployment_server.yml'
  when: edge_image_builder_deployment_server | bool
