---
- name: 'Assert supported system'
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == 'RedHat'

- name: 'Ensure dependencies'
  ansible.builtin.package:
    name:
      - 'osbuild-composer'
      - 'composer-cli'
      - 'httpd'
    state: 'present'
  notify: 'Reboot system'

- name: 'Ensure firewall ports'
  ansible.posix.firewalld:
    service: "{{ firewall_service }}"
    permanent: true
    immediate: true
    state: 'enabled'
  loop:
    - 'dhcp'
    - 'tftp'
    - 'http'
  loop_control:
    loop_var: 'firewall_service'

- name: 'Ensure services'
  ansible.builtin.service:
    name: "{{ service }}"
    state: 'started'
    enabled: true
  loop:
    - 'osbuild-composer.socket'
    - 'httpd.service'
  loop_control:
    loop_var: 'service'

- name: 'Get distro ID'
  ansible.builtin.shell: |
    set -o pipefail
    . /etc/os-release
    echo $ID
  register: 'edge_image_builder_distro_id_raw'
  changed_when: false

- name: 'Set fact for distro ID'
  ansible.builtin.set_fact:
    edge_image_builder_distro_id: "{{ edge_image_builder_distro_id_raw['stdout'] }}-{{ ansible_facts['distribution_major_version'] }}"

- name: 'Ensure directories'
  ansible.builtin.file:
    path: "{{ directory }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  loop:
    - '/etc/osbuild-composer/repositories'
    - '/etc/osbuild-composer/blueprints'
    - '/etc/osbuild-worker'
    - '/var/lib/tftpboot/pxelinux.cfg'
  loop_control:
    loop_var: 'directory'

- name: 'Ensure Pullsecret for osbuild-worker'
  when: edge_image_builder_pull_secret | length > 0
  notify: 'Reboot system'
  block:
    - name: 'Configure pull-secret.json'
      ansible.builtin.copy:
        content: "{{ edge_image_builder_pull_secret }}"
        dest: '/etc/osbuild-worker/pull-secret.json'
        owner: 'root'
        group: 'root'
        mode: '0600'
    - name: 'Configure osbuild-worker'
      ansible.builtin.template:
        src: 'osbuild-worker.toml.j2'
        dest: '/etc/osbuild-worker/osbuild-worker.toml'
        owner: 'root'
        group: 'root'
        mode: '0644'

- name: 'Ensure default repository overrides'
  ansible.builtin.template:
    src: "{{ edge_image_builder_distro_id }}.json.j2"
    dest: "/etc/osbuild-composer/repositories/{{ edge_image_builder_distro_id }}.json"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart osbuild-composer'

- name: 'Ensure extra repo definitions'
  ansible.builtin.template:
    src: 'osbuild-composer-repo.toml.j2'
    dest: "/etc/osbuild-composer/repositories/{{ repo['id'] }}.toml"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ edge_image_builder_repos }}"
  loop_control:
    loop_var: 'repo'

- name: 'Import extra repo definitions'
  ansible.builtin.command: /usr/bin/composer-cli sources add /etc/osbuild-composer/repositories/{{ repo['id'] }}.toml
  changed_when: true  # The command does not tell you if anything has changed
  loop: "{{ edge_image_builder_repos }}"
  loop_control:
    loop_var: 'repo'

- name: 'Configure deployment server'
  ansible.builtin.include_tasks: 'tasks/deployment_server.yml'
  when: edge_image_builder_deployment_server | bool

- name: 'Build blueprints'
  when: edge_image_builder_make_blueprints | bool
  block:
    - name: 'Make a list of all available blueprints'
      ansible.builtin.find:
        paths: '/etc/osbuild-composer/blueprints'
        patterns: '*.toml'
        file_type: 'file'
      register: 'edge_image_builder_blueprint_files'

    - name: 'Collect blueprint filenames'
      ansible.builtin.set_fact:
        edge_image_builder_blueprints: "{{ (edge_image_builder_blueprints | default([])) + [item | basename | regex_replace('.toml', '')] }}"
      loop: "{{ edge_image_builder_blueprint_files['files'] | map(attribute='path') }}"

    - name: 'Build blueprint'
      ansible.builtin.include_tasks: 'tasks/make_blueprint.yml'
      loop: "{{ edge_image_builder_blueprints }}"
      loop_control:
        loop_var: 'blueprint'

    - name: 'Update PXEboot menu'
      ansible.builtin.template:
        src: "{{ pxeboot['name'] }}"
        dest: "/var/lib/tftpboot/{{ pxeboot['dest'] }}"
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop:
        - name: 'pxelinux.cfg.j2'
          dest: 'pxelinux.cfg/default'
        - name: 'grub.cfg.j2'
          dest: 'grub.cfg'
      loop_control:
        loop_var: 'pxeboot'
