---
- name: 'Reboot system'
  ansible.builtin.reboot:

- name: 'Restart osbuild-composer'
  ansible.builtin.service:
    name: 'osbuild-composer.service'
    state: 'restarted'

- name: 'Restart dhcpd'
  ansible.builtin.service:
    name: 'dhcpd'
    state: 'restarted'
